apiVersion: v1
kind: Service
metadata:
    name: "aultestchange-35ad"
    labels:
        app: "aultestchange-35ad"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aultestchange-35ad"