on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aultest.azurecr.io
        username: ${{ secrets.acr_aultest_username }}
        password: ${{ secrets.acr_aultest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CoreWeb/CoreWeb" -f  "CoreWeb/CoreWeb/Dockerfile" -t aultest.azurecr.io/aultestchange:${{ github.sha }}
        docker push aultest.azurecr.io/aultestchange:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aultestchange_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aul-test-changeb092 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aul-test-changeb092`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aul-test-changeb092
        container-registry-url: aultest.azurecr.io
        container-registry-username: ${{ secrets.acr_aultest_username }}
        container-registry-password: ${{ secrets.acr_aultest_password }}
        secret-name: aultestchangdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aul-test-changeb092
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          aultest.azurecr.io/aultestchange:${{ github.sha }}
        imagepullsecrets: |
          aultestchangdockerauth